---
- name: DNM PRINT-5
  ansible.builtin.debug:
    msg: "{{ item }}"

- name: DNM PRINT-6
  ansible.builtin.debug:
    msg: "{{ ansible_network_os }}" 

- name: Run the platform facts module
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
    name: "{{ ansible_network_os }}_{{ item }}"
    state: gathered
  register: result

- name: Resource Facts
  ansible.builtin.debug:
    msg: "{{ result }}"
  when:
    - action != 'persist'

- name: Include file write task
  ansible.builtin.include_tasks: includes/write_to_file.yaml
  when:
    - action == 'persist'
    - ignore_empty is undefined
    - result["gathered"] != {}
    - result["gathered"] != []

- name: Include file write task
  ansible.builtin.include_tasks: includes/write_to_file.yaml
  when:
    - action == 'persist'
    - ignore_empty is defined
