---
name: Release

on:   # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_ah.yaml@main
    with:
      environment: ah
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}